### PR TITLE
creating BE structure and entities except for Specifications 

### PR DESCRIPTION
**Pull request by tuankiet2640**
creating BE structure and entities except for Specifications

### CODE REVIEW

**Review by MinhThang2709 — APPROVED** [review]
LGTM

**Review by MinhThang2709 — APPROVED** [review]

**Comment by MinhThang2709** [comment]
LGTM

**Review by kyphuc99 — APPROVED** [review]
Well done

**Review by kyphuc99 — APPROVED** [review]
LGTM

**Review by TRANHUUTINH — APPROVED** [review]
LGTM

**Pull request merged**
